### ISSUE TITLE
Register GPU machine for Cuda builds through gitlab.com

### ISSUE THREAD

**Issue by junghans** [ECP-copa/Cabana#19]
Here is how you register a runner:
https://docs.gitlab.com/runner/register/

then we need to modify our `.gitlab-ci.yml` to use that runner on bare metal.

**Comment by dalg24** [comment]
#74 proposes Cuda testing using a ORNL Jenkins CI server and slave machine with a Volta GPU.

@junghans suggested we register a specific gitlab runner instead.  I did not realize GitLab was able to mirror GitHub PRs initiated from forks (instead of a branch on the main repo).  I am fine closing #74 and setting up a new entry in the `.gitlab-ci.yml` and register a new runner.

@sslattery  What do you think?

**Comment by sslattery** [comment]
If it does what we want it to do, is just as easy to maintain as the Jenkins route, and is consistent with the current CI then I am fine closing #74

**Comment by dalg24** [comment]
Reopened #78 and closed #79 since GitLab CI does not support PRs initiated from GH forks at the moment.  We got confused because the mirroring on GitLab on manually reset and all PRs opened at that time triggered a build.

**Comment by dalg24** [comment]
I disabled the gitlab-runner with the GPU but I can restart it if we reopen #78 in the future.

**Comment by dalg24** [comment]
I recommend we close this issue and move it to the backlog.  @junghans ?
