### ISSUE TITLE
Neighbor List Time/Space Complexity

### ISSUE THREAD

**Issue by ejm930** [ECP-copa/Cabana#293]
I'm currently trying to a create NL on the gpu for 10^6 particle with positions following a uniform random distribution in a 1x1x1 cube. With a neighbourhood_radius = 0.1 and a cell_ratio = 1.0 it runs fine. But, as soon as I ramp up the particles, make the radius smaller, or increase the cell_ratio things tend to get really slow or I run out of memory. 

My questions:

1) Is there a specific paper this implementation is based on that I can check out?
2) Any way to get the space and time complexity for the specific algorithm used added to the doc?
3) If possible, would you be able to provide a brief explanation on how to tweak the cell ratio for optimal performance?

Thanks in advanced for my naive questions.

**Comment by streeve** [comment]
First, for your questions:

1. Here's one good paper: https://arxiv.org/abs/physics/0311055v1 (I'm pointing to an earlier version here because this is closest to what our implementation currently does)
2. That's a good suggestion and we're always trying to improve our documentation; we have performance tests that I could use to test and show this. Because of the linked cell list, this is O(N)
3. For many cases, cell size ratio of 1.0 will be most optimal - this is relative to the cutoff radius, so with 1.0 you ensure you only need to search one layer of cells surrounding the one the central particle occupies. With other values, you either search through many more atoms in each cell or many more cells.

Some more context would help me: what types of problems are you interested in? Are your cases of interest actually at such high density that this implementation is currently very slow or runs out of memory? 

Our implementation comes largely from molecular dynamics and I work mainly with normal density atomic systems, but it's quite possible to go beyond those conditions.

**Comment by ejm930** [comment]
Thanks for the paper source! So, it sounds like the cell ratio is a delicate balance/trade-off. 

As for context, I'm interested in simulating complex biological systems. The simplest case could be a reaction network where we have A+B -> C. Say we start with 10^6 of A and 10^4 of B, the goal would be to simulate all of these events exactly, which would require knowing all the positions of of A, B in order to find all occurrences of A's near B's . This is a fairly trivial problem that could be solved by a set of ODES, which makes is a great test. 

My target case is a bit more complicated and involves graphs. But either way, I'm starting small with a system on the order of 10^4 first. I haven't done any sort of density calculation yet, but I'd like to say on average, I'd expect every particle to have ~5-40 neighbours depending on conditions.

I guess to summarize, what I'd really like to do is figure out how large and dense of a system I squeeze onto a gpu, while making the most of Cabana and not running out memory or taking more than say 30-300 microseconds to compute a NL. 

Btw, I'm on the Cabana-slack via Bob, so just let me know if it's more reasonable to continue this conversation there.

**Comment by streeve** [comment]
Thanks for the info. Yes, I think slack will make it easier to discuss. We can discuss and determine any items needed to close this
