### ISSUE TITLE
AoSoA type ordering issue

### ISSUE THREAD

**Issue by HenryCullom** [ECP-copa/Cabana#579]
While working with the AoSoA type, I came across a strange issue when trying to fill it with many different types in no particular order. If you initialize the AoSoA with more than 32 tuples, the assertion on line 51 fails. I made another attempt with the same types but ordered by size descending, and it worked perfectly. The documentation for the AoSoA states:

>We recommend listing larger data types first and like types sequentially to ensure a minimal amount of storage of tuple data. Storage sizes of tuple data (even for the SoA and AoS examples above) can vary depending on the order of the data members due to padding to satisfy alignment requirements.

but it seems like not ordering them in this scenario can result in failures and/or unexpected behavior. Below is a link to some example code where this issue appears. Let me know if this is just me making a mistake or if the ordering can cause problems larger than just performance issues.

When using the Kokkos::Serial execution space, both orderings appear to work as expected. The failures occur only when using the CUDA backend.

compiling with gcc version 10.1.0
using Cabana version 0.5.0, Kokkos version 3.7.0, CUDA version 11.4

https://gist.github.com/HenryCullom/fe38b4c932c76f336b69b65e42f83742

**Comment by streeve** [comment]
I'll take a look - thanks for the detail and clear example

**Comment by weinbe2** [comment]
The underlying issue is likely related to how (as you noted above) there is a padding difference between the two orderings --- in particular, `double` and `float` tend to assume 8-byte and 4-byte alignment, respectively, and the `char`s and `short int` break that with the initial ordering. A compiler will likely insert extra padding to keep the `double`, `float`, etc appropriately aligned.

On the other hand, the SoA may not have the same padding issues because it turns into arrays of `char` and arrays of `short int`, etc, the full static arrays of which likely do line up on 4- and 8-byte boundaries, etc. In practice this could turn into `vec_length * sizeof(tuple) > sizeof(SoA)`.

I put together a quick (albeit noisy) mini-app that can be used to test this:
```
#include <stdio.h>

struct tuple_ordered { long double a; double b; double c; long unsigned int d; float e; int f; short int g; char h; char i; };

struct tuple_ordered_array { long double a[32]; double b[32]; double c[32]; long unsigned int d[32]; float e[32]; int f[32]; short int g[32]; char h[32]; char i[32]; };

struct tuple_disordered { double a; short int b; float c; char d; int e; char f; double g; long unsigned int h; long double i; };

struct tuple_disordered_array { double a[32]; short int b[32]; float c[32]; char d[32]; int e[32]; char f[32]; double g[32]; long unsigned int h[32]; long double i[32]; };

__global__ void kernel() {
  printf("CUDA sizeof(tuple_ordered) == %lu alignof(tuple_ordered) == %lu\n", sizeof(tuple_ordered), alignof(tuple_ordered));
  printf("CUDA sizeof(tuple_ordered_array) == %lu alignof(tuple_ordered_array) == %lu\n", sizeof(tuple_ordered_array), alignof(tuple_ordered_array));
  printf("CUDA sizeof(tuple_disordered) == %lu alignof(tuple_disordered) == %lu\n", sizeof(tuple_disordered), alignof(tuple_disordered));
  printf("CUDA sizeof(tuple_disordered_array) == %lu alignof(tuple_disordered_array) == %lu\n", sizeof(tuple_disordered_array), alignof(tuple_disordered_array));
}

int main(int argc, char** argv) {

  printf("CPU sizeof(tuple_ordered) == %lu alignof(tuple_ordered) == %lu\n", sizeof(tuple_ordered), alignof(tuple_ordered));
  printf("CPU sizeof(tuple_ordered_array) == %lu alignof(tuple_ordered_array) == %lu\n", sizeof(tuple_ordered_array), alignof(tuple_ordered_array));
  printf("CPU sizeof(tuple_disordered) == %lu alignof(tuple_disordered) == %lu\n", sizeof(tuple_disordered), alignof(tuple_disordered));
  printf("CPU sizeof(tuple_disordered_array) == %lu alignof(tuple_disordered_array) == %lu\n", sizeof(tuple_disordered_array), alignof(tuple_disordered_array));

  printf("CPU Alignment test:\n");
  {
    // Explicitly compute the offsets of each element
    tuple_ordered* to = new tuple_ordered;
    unsigned long long addr_to = (unsigned long long) to;
    unsigned long long addr_a = (unsigned long long)(&to->a) - addr_to;
    unsigned long long addr_b = (unsigned long long)(&to->b) - addr_to;
    unsigned long long addr_c = (unsigned long long)(&to->c) - addr_to;
    unsigned long long addr_d = (unsigned long long)(&to->d) - addr_to;
    unsigned long long addr_e = (unsigned long long)(&to->e) - addr_to;
    unsigned long long addr_f = (unsigned long long)(&to->f) - addr_to;
    unsigned long long addr_g = (unsigned long long)(&to->g) - addr_to;
    unsigned long long addr_h = (unsigned long long)(&to->h) - addr_to;
    unsigned long long addr_i = (unsigned long long)(&to->i) - addr_to;
    printf("   Ordered explicit offset: addr_a %llu, addr_b %llu, add_cr %llu, addr_d %llu, addr_e %llu, addr_f %llu, addr_g %llu, addr_h %llu, addr_i %llu, end %lu\n", addr_a, addr_b, addr_c, addr_d, addr_e, addr_f, addr_g, addr_h, addr_i, sizeof(tuple_ordered));
    // Naively compute the offsets via a sum of the datatypes:
    unsigned long long prefix_sum = 0;
    printf("   Ordered naive sum:       addr_a %llu, ", prefix_sum);
    prefix_sum += sizeof(long double); printf("addr_b %llu, ", prefix_sum);
    prefix_sum += sizeof(double); printf("addr_c %llu, ", prefix_sum);
    prefix_sum += sizeof(double); printf("addr_d %llu, ", prefix_sum);
    prefix_sum += sizeof(long unsigned int); printf("addr_e %llu, ", prefix_sum);
    prefix_sum += sizeof(float); printf("addr_f %llu, ", prefix_sum);
    prefix_sum += sizeof(int); printf("addr_g %llu, ", prefix_sum);
    prefix_sum += sizeof(short int); printf("addr_h %llu, ", prefix_sum);
    prefix_sum += sizeof(char); printf("addr_i %llu, ", prefix_sum);
    prefix_sum += sizeof(char); printf("end %llu\n", prefix_sum);
    delete to;
  }

  {
    // Explicitly compute the offsets of each element
    tuple_disordered* to = new tuple_disordered;
    unsigned long long addr_to = (unsigned long long) to;
    unsigned long long addr_a = (unsigned long long)(&to->a) - addr_to;
    unsigned long long addr_b = (unsigned long long)(&to->b) - addr_to;
    unsigned long long addr_c = (unsigned long long)(&to->c) - addr_to;
    unsigned long long addr_d = (unsigned long long)(&to->d) - addr_to;
    unsigned long long addr_e = (unsigned long long)(&to->e) - addr_to;
    unsigned long long addr_f = (unsigned long long)(&to->f) - addr_to;
    unsigned long long addr_g = (unsigned long long)(&to->g) - addr_to;
    unsigned long long addr_h = (unsigned long long)(&to->h) - addr_to;
    unsigned long long addr_i = (unsigned long long)(&to->i) - addr_to;
    printf("Disordered explicit offset: addr_a %llu, addr_b %llu, add_c %llu, addr_d %llu, addr_e %llu, addr_f %llu, addr_g %llu, addr_h %llu, addr_i %llu, end %lu\n", addr_a, addr_b, addr_c, addr_d, addr_e, addr_f, addr_g, addr_h, addr_i, sizeof(tuple_disordered));
    // Naively compute the offsets via a sum of the datatypes:
    unsigned long long prefix_sum = 0;
    printf("Disordered naive sum:       addr_a %llu, ", prefix_sum);
    prefix_sum += sizeof(double); printf("addr_b %llu, ", prefix_sum);
    prefix_sum += sizeof(short int); printf("addr_c %llu, ", prefix_sum);
    prefix_sum += sizeof(float); printf("addr_d %llu, ", prefix_sum);
    prefix_sum += sizeof(char); printf("addr_e %llu, ", prefix_sum);
    prefix_sum += sizeof(int); printf("addr_f %llu, ", prefix_sum);
    prefix_sum += sizeof(char); printf("addr_g %llu, ", prefix_sum);
    prefix_sum += sizeof(double); printf("addr_h %llu, ", prefix_sum);
    prefix_sum += sizeof(long unsigned int); printf("addr_i %llu, ", prefix_sum);
    prefix_sum += sizeof(long double); printf("end %llu\n", prefix_sum);
    delete to;
  }

  kernel<<<1,1>>>();
  fflush(stdout);
  cudaDeviceSynchronize();
  return 0;
```

In lieu of using `tuple`s I just used structs, a means to the same end, where `tuple_ordered` and `tuple_disordered` corresponds to the ordered and unordered list of types, respectively. Similiarly, in lieu of a Cabana `SoA`, I created `*_array` versions that add the `[32]` that you'd have with the CUDA backend (corresponding to the warp type). This code measures the sizes and alignments of the different structs (on both the CPU and GPU), and then also directly probes the padding by computing the differences between pointer offsets (particularly gross code).

The outputs on my machine are:

```
> nvcc -std=c++11 main.cu -o test
> ./test
CPU sizeof(tuple_ordered) == 64 alignof(tuple_ordered) == 16
CPU sizeof(tuple_ordered_array) == 1664 alignof(tuple_ordered_array) == 16
CPU sizeof(tuple_disordered) == 64 alignof(tuple_disordered) == 16
CPU sizeof(tuple_disordered_array) == 1664 alignof(tuple_disordered_array) == 16
CPU Alignment test:
   Ordered explicit offset: addr_a 0, addr_b 16, add_cr 24, addr_d 32, addr_e 40, addr_f 44, addr_g 48, addr_h 50, addr_i 51, end 64
   Ordered naive sum:       addr_a 0, addr_b 16, addr_c 24, addr_d 32, addr_e 40, addr_f 44, addr_g 48, addr_h 50, addr_i 51, end 52
Disordered explicit offset: addr_a 0, addr_b 8, add_c 12, addr_d 16, addr_e 20, addr_f 24, addr_g 32, addr_h 40, addr_i 48, end 64
Disordered naive sum:       addr_a 0, addr_b 8, addr_c 10, addr_d 14, addr_e 15, addr_f 19, addr_g 20, addr_h 28, addr_i 36, end 52
CUDA sizeof(tuple_ordered) == 64 alignof(tuple_ordered) == 16
CUDA sizeof(tuple_ordered_array) == 1664 alignof(tuple_ordered_array) == 16
CUDA sizeof(tuple_disordered) == 64 alignof(tuple_disordered) == 16
CUDA sizeof(tuple_disordered_array) == 1664 alignof(tuple_disordered_array) == 16
```

 * We see the CPU and GPU both agree that the data structures are 64 bytes, 16 byte aligned, for both the ordered and disordered list. This is in contrast to a naive summing of the sizes of the data types, which would give **52 bytes**.
 * The CPU and GPU both also agree on the size of the "SoA", 1664 bytes, which is what you'd naively expect: `52 * 32 == 1664` --- so `32 * sizeof(tuple) != sizeof(SoA)`
 * The offset math gets confusing, but in brief, we see that there is no unexpected padding, i.e., nothing but extra padding at the end, in the "tuple" when the data types are sorted by descending size; copying from above:
```
   Ordered explicit offset: addr_a 0, addr_b 16, add_cr 24, addr_d 32, addr_e 40, addr_f 44, addr_g 48, addr_h 50, addr_i 51, end 64
   Ordered naive sum:       addr_a 0, addr_b 16, addr_c 24, addr_d 32, addr_e 40, addr_f 44, addr_g 48, addr_h 50, addr_i 51, end 52
```
 * However, when the data sizes are more random, there is a disagreement:
```
Disordered explicit offset: addr_a 0, addr_b 8, add_c 12, addr_d 16, addr_e 20, addr_f 24, addr_g 32, addr_h 40, addr_i 48, end 64
Disordered naive sum:       addr_a 0, addr_b 8, addr_c 10, addr_d 14, addr_e 15, addr_f 19, addr_g 20, addr_h 28, addr_i 36, end 52
```

What all this suggests is there could be tension in how Cabana figures out offsets for Slices --- depending on if it bases it off a "naive" prefix sum, `sizeof(Tuple)`, `sizeof(SoA)...`, etc. Depending on how/if/where that calculation includes padding, a "write" into the first SoA (vector index 0, 1, ..., 31) may actually end up writing to something into the memory space for the second SoA --- this could happen if the offset is based off the `sizeof(Tuple)`, which has padding, as opposed to `sizeof(SoA) == 1664`, which doesn't. On face value, this would create an out of bounds memory access error, but it's possible that extra padding gets added to the memory allocations as well, so these data accesses are technically legal. Valgrind or whatnot should uncover this (and/or Kokkos's View bounds range checking, but I'm not sure how that'll play with Cabana.)

Now, with that said --- the reason why it still may just be "fine" on the CPU and cause a problem on the GPU is because on the CPU it's serialized --- element 0, 1, 2, ..., 31, 32, 33 get written then read sequentially with the `Serial` backend. On the other hand, in CUDA, work is done concurrently in units of warps (32 threads), so the work done by threads 0, 1, 2, ... 31 is being done concurrently with work done by threads (32, 33, ..., 63) in the second warp. If there are indeed the padding woes I describe above, this could be why everything is fine up to 32 tuples, then breaks when you get to 33 --- a combination of padding headaches + threads trampling each other (a thread in warp 0 writes, a thread in warp 1 writes, a thread in warp 0 reads...). This is something that could be checked by a race checker.

It's unreasonable (if not essentially impossible) for Cabana to predict and "deal" with these type of padding considerations, especially at compile time. The comment on ordering data types from largest to smallest is relevant because it ~infinitely less likely there will be padding headaches in the _middle_ of a Tuple, and extra padding at the end of a Tuple is far less likely to be a problem, since the offset into any one actual element of the `Tuple` doesn't need to "care" about padding at the end.

...there's a lot here, including messy code, so let me know what you think or wish for any clarifications.

**Comment by streeve** [comment]
Feel free to reopen to ask a follow-up or related question or open a new issue as needed
