### ISSUE TITLE
ArborX neighborlist interface compile error

### ISSUE THREAD

**Issue by streeve** [ECP-copa/Cabana#726]
Nightly build fails using ArborX master

```
/__w/Cabana/Cabana/core/unit_test/tstNeighborListArborX.hpp:96:66:   required from here
/github/home/arborx/include/ArborX/details/ArborX_Callbacks.hpp:90:9: error: no type named 'Tag' in 'using Predicate = using value_type = std::decay_t<Kokkos::nonesuch>' {aka 'std::decay<Kokkos::nonesuch>::type'}
   90 |   using PredicateTag = typename Predicate::Tag;
      |         ^~~~~~~~~~~~
/github/home/arborx/include/ArborX/details/ArborX_Callbacks.hpp:99:55: error: no type named 'Tag' in 'using value_type = std::decay_t<Kokkos::nonesuch>' {aka 'std::decay<Kokkos::nonesuch>::type'}
   99 |   static_assert(is_valid_predicate_tag<PredicateTag>::value &&
      |                                                       ^~~~~
```

**Comment by streeve** [comment]
@aprokop is this is an easy fix?

**Comment by aprokop** [comment]
@streeve Where can I see the full log?

**Comment by streeve** [comment]
https://github.com/ECP-copa/Cabana/actions/runs/7381454600/job/20080001545

**Comment by aprokop** [comment]
The problem is this part: https://github.com/ECP-copa/Cabana/blob/973e7d0722ddb2503a3c5cb9220410a7666768e4/core/src/Cabana_Experimental_NeighborList.hpp#L99-L100.

Users are only allowed to specialize `AccessTraits` for their own data. As the code in question is templated on any template `Slice`, it spreads to ArborX internals resulting in a conflict.

The way to fix it is to template on something Cabana. I'm not sure what the general Cabana slice template slice is. Would probably need something like
```c++
template<typename... Args>
struct AccessTraits<Cabana::Slice<Args...>
```
I'm trying it out, but something isn't working right now.

**Comment by dalg24** [comment]
I suppose I should have read this before I opened #728 
The predicate access traits are to blame.  The primitive ones are fine.
Essentially doing the same thing as Andrey.  I like better his calling the alias `SliceLike` rather than `Self`.  The `decay_t` in the `get` member function in unnecessary.  I went for a `remove_const_t` for the one computing `n_queries` but that gives the same thing,
